# Generated by Django 4.1.3 on 2022-11-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
